[ftplugin]
_='''
'''

vim='''
setlocal shiftwidth=2
setlocal tabstop=2
'''

toml='''
setlocal shiftwidth=2
setlocal tabstop=2
'''

pug='''
setlocal shiftwidth=2
setlocal tabstop=2
'''

javascript='''
set tabstop=2
set shiftwidth=2
'''

json='''
let g:vim_json_syntax_conceal = 0
setlocal conceallevel=0
setlocal concealcursor=
'''

denite='''
setlocal winblend=30
'''

denite-filter='''
setlocal winblend=30
'''
