[ftplugin]
_='''
'''

vim='''
setlocal shiftwidth=2
setlocal tabstop=2
'''

toml='''
setlocal shiftwidth=2
setlocal tabstop=2
'''

pug='''
setlocal shiftwidth=2
setlocal tabstop=2
'''

javascript='''
set tabstop=2
set shiftwidth=2
'''

json='''
setlocal conceallevel=0
setlocal concealcursor=
'''
