local gitsigns = require('gitsigns')
gitsigns.setup()
local map = require 'functions'.map
map('n', '<leader>hS', '<cmd>lua require("gitsigns").stage_buffer()<cr>')
map('n', '<leader>hR', '<cmd>lua require("gitsigns").reset_buffer()<cr>')
map('n', '<leader>hp', '<cmd>lua require("gitsigns").preview_hunk()<cr>')
map('n', '<leader>hi', '<cmd>lua require("gitsigns").preview_hunk_inline()<cr>')
map('n', '<leader>hb', '<cmd>lua require("gitsigns").blame_line({ full = true})<cr>')
map('n', '<leader>hd', '<cmd>lua require("gitsigns").diffthis()<cr>')
map('n', '<leader>hs', '<cmd>lua require("gitsigns").stage_hunk()<cr>')
map('n', '<leader>hr', '<cmd>lua require("gitsigns").reset_hunk()<cr>')
map('v', '<leader>hs', '<cmd>lua require("gitsigns").stage_hunk({vim.fn.line("."), vim.fn.line("v")})<cr>')
map('v', '<leader>hr', '<cmd>lua require("gitsigns").reset_hunk({vim.fn.line("."), vim.fn.line("v")})<cr>')
map('n', ']h', '<cmd>lua require("gitsigns").next_hunk()<cr>')
map('n', '[h', '<cmd>lua require("gitsigns").prev_hunk()<cr>')
