[[plugins]]
repo = 'Shougo/dein.vim'
[[plugins]]
repo = 'sophacles/vim-processing'
[[plugins]]
repo = 'w0rp/ale'
[[plugins]]
repo = 'jceb/vim-hier'
[[plugins]]
repo = 'Shougo/vimproc.vim'
hook_post_update = '''
  if dein#util#_is_windows()
    let cmd = 'tools\\update-dll-mingw'
  elseif dein#util#_is_cygwin()
    let cmd = 'make -f make_cygwin.mak'
  elseif executable('gmake')
    let cmd = 'gmake'
  else
    let cmd = 'make'
  endif
  let g:dein#plugin.build = cmd
'''
[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'
hook_add = '''
    let g:indent_guides_enable_on_vim_startup = 1
    let g:indent_guides_color_change_percent = 6
    let g:indent_guides_start_level = 2
    let g:indent_guides_guide_size = 1
    let g:indent_guides_auto_colors = 0
    augroup MyAutoCmd
        autocmd VimEnter,Colorscheme * :hi IndentGuidesOdd  ctermbg=8
        autocmd VimEnter,Colorscheme * :hi IndentGuidesEven ctermbg=7
    augroup END
'''
[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
    let g:lightline = { 
    \   'colorscheme': 'wombat'
    \}
'''
[[plugins]]
repo = 'dracula/vim'
hook_add = '''
    let g:dracula_colorterm = 0
'''
[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
"    au MyAutoCmd Vimenter * NERDTree
    map <C-q> :NERDTreeToggle<CR>
    autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif
'''
[[plugins]]
repo = 'mattn/webapi-vim'
[[plugins]]
repo = 'kana/vim-metarw'
[[plugins]]
repo = 'mattn/vim-metarw-gdrive'
depends = ['mattn/webapi-vim', 'kana/vim-metarw']
[[plugins]]
repo = 'Shougo/denite.nvim'
[[plugins]]
repo = 'tyru/open-browser.vim'
[[plugins]]
repo = 'previm/previm'
depends = ['tyru/open-browser.vim']
