[[plugins]]
repo = 'Shougo/dein.vim'
[[plugins]]
repo = 'sophacles/vim-processing'
[[plugins]]
repo = 'w0rp/ale'
[[plugins]]
repo = 'jceb/vim-hier'
[[plugins]]
repo = 'Shougo/vimproc.vim'
hook_post_update = '''
  if dein#util#_is_windows()
    let cmd = 'tools\\update-dll-mingw'
  elseif dein#util#_is_cygwin()
    let cmd = 'make -f make_cygwin.mak'
  elseif executable('gmake')
    let cmd = 'gmake'
  else
    let cmd = 'make'
  endif
  let g:dein#plugin.build = cmd
'''
[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'
[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
    let g:lightline = { 
    \   'colorscheme': 'wombat'
    \}
'''
[[plugins]]
repo = 'tomasr/molokai'
hook_add = '''
    set background=dark
    au MyAutoCmd VimEnter * nested colorscheme molokai
    let g:molokai_original = 1
    let g:rehash256 = 1
    syntax on
'''
[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
    au MyAutoCmd Vimenter * NERDTree
'''
