[[plugins]]
repo='Shougo/deoplete.nvim'
hook_source = '''
    let g:deoplete#enable_at_startup = 1
'''
on_i = 1
[[plugins]]
repo='cohama/lexima.vim'
on_i = 1
[[plugins]]
repo='Shougo/neosnippet.vim'
depends=['neosnippet-snippets']
on_i = 1
on_ft = ['snippet']
hook_source = '''
    imap <C-k> <Plug>(neosnippet_expand_or_jump)
    smap <C-k> <Plug>(neosnippet_expand_or_jump)
    xmap <C-k> <Plug>(neosnippet_expand_target)

    smap <expr><TAB> neosnippet_expand_or_jumpable() ?
    \ "\<Plug>(neosnippet_expand_or_jump)" : "\<TAB>"

    if has('conceal')
        set conceallevel=2 concealcursor=niv
    endif
'''
[[plugins]]
repo='Shougo/neosnippet-snippets'
on_i = 1
[[plugins]]
repo = 'othree/html5.vim'
on_ft = ['html','js','css','php','tpl','vue']
[[plugins]]
repo = 'hail2u/vim-css3-syntax'
on_ft = ['html','js','css','php','tpl','vue']
[[plugins]]
repo = 'jelera/vim-javascript-syntax'
on_ft = ['html','js','css','php','tpl','vue']
[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['html','js','css','php','tpl','vue']
hook_add = '''
		let g:user_emmet_leader_key='<C-E>'
    let g:user_emmet_mode = 'inv'
    let g:use_emmet_complete_tag = 1
    let g:user_emmet_settings = {
    \   'variables': {
    \       'lang': "ja"
    \   },
    \   'indentation': '    '
    \}
'''
